GET http://localhost:8080/recipes?page=1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYW5pbGluZjEzMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hdXRoL3Rva2VuIiwiZXhwIjoxNjg1OTc2NTY4fQ.zRIcHMXPUI4clZP_goPQrgxd3b7zCfRdE5fzwB88cO8
###
GET http://localhost:8080/recipes/my
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYW5pbGluZjEzMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hdXRoL3Rva2VuIiwiZXhwIjoxNjg1OTc2NTY4fQ.zRIcHMXPUI4clZP_goPQrgxd3b7zCfRdE5fzwB88cO8
###
GET http://localhost:8080/profile
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYW5pbGluZjEzMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hdXRoL3Rva2VuIiwiZXhwIjoxNjg1OTc2NTY4fQ.zRIcHMXPUI4clZP_goPQrgxd3b7zCfRdE5fzwB88cO8

### Get token
POST http://localhost:8080/auth/token
Content-Type: application/x-www-form-urlencoded

email=danilinf131@gmail.com&password=1

### Refresh token
POST http://localhost:8080/auth/token
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYW5pbGluZjEzMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hdXRoL3Rva2VuIiwiZXhwIjoxNjg1OTc2MTQ4fQ.fSZGFjL2L0noT2wzzgfe2jrrgxG-VurAT1nG9kn5im0

### Revoke token
POST http://localhost:8080/auth/token/revoke
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYW5pbGluZjEzMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hdXRoL3Rva2VuIiwiZXhwIjoxNjg1OTc2MjA2fQ.aQfad27wlsjhu-_iFIwwRcm7WbIVZfYxQVxpUfiDB8w

###
POST http://localhost:8080/signup
Content-Type: application/json

{
"email": "danilinf131@gmail.com",
"password": "1",
"firstName": "danil",
"lastName": "lin"
}

###

GET http://localhost:8080/recipes/19
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYW5pbGluZjEzMUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2F1dGgvdG9rZW4iLCJleHAiOjE2ODU3MzUzOTZ9.74rgyEOK_HQ_cNAPC2XR0dPLUOocC7a2dlPLMqBKNc4

