GET http://localhost:80/recipes?page=0
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYW5pbGluZjEzMUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2F1dGgvdG9rZW4iLCJleHAiOjE2ODEwNDA4Mjh9.chh1IKwWjtJWpqNAuyIOg0xkRljdMRQLez6Z6Dqe-kY
###
POST http://localhost:80/auth/token
Content-Type: application/x-www-form-urlencoded

email=danilinf131@gmail.com&password=1

###

POST http://localhost:80/recipes
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYW5pbGluZjEzMUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2F1dGgvdG9rZW4iLCJleHAiOjE2ODEwNjk3MzF9.x4LsEBHTthvG95DJ5_JD3is2WG1zzm9WgcCGUuu8UUM
Content-Type: application/json

{
  "name": "6",
  "tags": "sort test"
}