version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis_volume:/data

  app:
    depends_on:
      - postgres
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/javalab23
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '8080:8080'

volumes:
  postgres_volume:
  redis_volume: